### ISSUE TITLE
Uncaught ReferenceError: editor is not defined

### ISSUE THREAD

**Issue by snaumov** [clessg/atom-expand-selection-to-quotes#12]
Hi, I'm getting subj error, here is stacktrace

`/home/stepan/.atom/packages/expand-selection-to-quotes/lib/expand-selection-to-quotes.coffee:16
Hide Stack Trace
ReferenceError: editor is not defined
    at new ExpandSelectionToQuotes (/home/stepan/.atom/packages/expand-selection-to-quotes/lib/expand-selection-to-quotes.coffee:16:16)
    at atom-text-editor.<anonymous> (/home/stepan/.atom/packages/expand-selection-to-quotes/lib/expand-selection-to-quotes.coffee:55:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:59)`

Atom 1.12.1, ubuntu 16.04

**Comment by rajankur** [comment]
Edit your file and add the following in _/home/stepan/.atom/packages/expand-selection-to-quotes/lib/expand-selection-to-quotes.coffee_ on **LINE 16**

```
editor = atom.workspace.getActiveTextEditor()
```

**Comment by clessg** [comment]
Apologies for the delay. This should now be fixed. Thanks!
